#!/usr/bin/env python3
"""Generate src/aowlunicode/segdata.nim: the UAX #29 break properties for
Intl.Segmenter (grapheme, word and sentence boundaries).

    python3 tools/gen_intl_seg.py UCD_DIR

UCD_DIR holds GraphemeBreakProperty.txt, WordBreakProperty.txt,
SentenceBreakProperty.txt, emoji-data.txt and DerivedCoreProperties.txt of
the Unicode version test262 targets (17.0.0).
"""
import sys, os, re

OUT = os.path.join(os.path.dirname(__file__), "..", "src", "aowlunicode", "segdata.nim")

GB = ["Other", "CR", "LF", "Control", "Extend", "ZWJ", "Regional_Indicator", "Prepend",
      "SpacingMark", "L", "V", "T", "LV", "LVT"]
WB = ["Other", "CR", "LF", "Newline", "Extend", "ZWJ", "Regional_Indicator", "Format",
      "Katakana", "Hebrew_Letter", "ALetter", "Single_Quote", "Double_Quote", "MidNumLet",
      "MidLetter", "MidNum", "Numeric", "ExtendNumLet", "WSegSpace"]
SB = ["Other", "CR", "LF", "Extend", "Sep", "Format", "Sp", "Lower", "Upper", "OLetter",
      "Numeric", "ATerm", "SContinue", "STerm", "Close"]
INCB = ["None", "Consonant", "Extend", "Linker"]

def read(path, names, prop_filter=None):
    ranges = []
    with open(path, encoding="utf-8") as f:
        for ln in f:
            ln = ln.split("#", 1)[0].strip()
            if not ln:
                continue
            parts = [p.strip() for p in ln.split(";")]
            if prop_filter:
                if parts[1] != prop_filter:
                    continue
                val = parts[2] if len(parts) > 2 else "Yes"
            else:
                val = parts[1]
            if val not in names:
                continue
            r = parts[0].split("..")
            a = int(r[0], 16)
            b = int(r[1], 16) if len(r) > 1 else a
            ranges.append((a, b, names.index(val)))
    ranges.sort()
    merged = []
    for a, b, v in ranges:
        if merged and merged[-1][2] == v and merged[-1][1] + 1 == a:
            merged[-1] = (merged[-1][0], b, v)
        else:
            merged.append((a, b, v))
    return merged

def emit(f, name, ranges):
    # one string literal per table (a huge array literal costs the compiler
    # far more): "first:length:value" hex entries, first delta-coded
    items = []
    prev = 0
    for a, b, v in ranges:
        items.append("%x:%x:%x" % (a - prev, b - a, v))
        prev = a
    f.write('const %s = "%s"\n\n' % (name, ",".join(items)))

def main():
    d = sys.argv[1]
    gb = read(os.path.join(d, "GraphemeBreakProperty.txt"), GB)
    wb = read(os.path.join(d, "WordBreakProperty.txt"), WB)
    sb = read(os.path.join(d, "SentenceBreakProperty.txt"), SB)
    ep = read(os.path.join(d, "emoji-data.txt"), ["", "Extended_Pictographic"])
    incb = read(os.path.join(d, "DerivedCoreProperties.txt"), INCB, "InCB")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("## Generated by tools/gen_intl_seg.py from the Unicode 17.0.0 UCD. Do not edit.\n")
        f.write("## Tables of (first, last, value) code point ranges.\n\n")
        emit(f, "segGraphemeProps", gb)
        emit(f, "segWordProps", wb)
        emit(f, "segSentenceProps", sb)
        emit(f, "segExtPict", ep)
        emit(f, "segInCB", incb)

if __name__ == "__main__":
    main()
